/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    PvAvatar: typeof import('primevue/avatar')['default']
    PvButton: typeof import('primevue/button')['default']
    PvInputText: typeof import('primevue/inputtext')['default']
    PvMenu: typeof import('primevue/menu')['default']
    PvMenubar: typeof import('primevue/menubar')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
